package driver;

import algorithms.Algorithm;

import java.io.File;
import java.util.Collection;
import java.util.List;
import java.util.Map;

/**
 * This interface provides a contract for the driver of the application.
 * @author darshan.panse
 *
 */
public interface IDriver {
	/**
	 * Setter for repoPaths.
	 * @param repoPaths a list of repository paths
	 */
	void setRepoPaths(List<String> repoPaths);
	
	/**
	 * Setter for hwDir.
	 * @param hwDir String
	 */
	void setHWDir(String hwDir);
	
	/**
	 * Gets the student data from the excel file provided by prof or TA
	 * and stores it as a map in the studentMap.
	 * @param xlsxFile File
	 * @return errorMessage String
	 */
	String getStudentData(File xlsxFile);
	
	/**
	 * Constructs the path to get the c files from the dir recursively.
	 * @param repoPath String
	 * @return String
	 */
	String constructPath(String repoPath);
	
	/**
	 * Gets the c files recursively from all the directories.
	 * @return errorMessage String
	 */
	String getCodeFiles();

	/**
	 * This method compares the similarity between the homework c files of two students
	 * and generates the summary. Also it returns false if the two students get paired
	 * for plagiarism (both high and medium probability).
	 * @param fileList1 a collection of files
	 * @param fileList2 another collection of files
	 * @param sp StudentPair a pair of students
	 */
	void computeSimilarityScore(Collection<File> fileList1, Collection<File> fileList2, IStudentPair sp);
	
	/**
	 * This method runs the algorithm on the homework c files of all the 
	 * selected student-repos and generates the Summary.
	 */
	void generateSummary();
	
	/**
	 * Employs a comparison strategy and compares all files of all students.
	 * @param repoPaths a list of repositories
	 * @param hwDir the homework directory to check
	 * @return errorMessage an error message if something goes wrong
	 */
	String checkForPlagiarism(List<String> repoPaths, String hwDir, Algorithm algo);
	
	/**
	 * This methods returns the Summary generated by the method generateSummary()
	 * @return Summary
	 */
	ISummary viewSummary();
	
	/**
	 * This method compares all the HW files of two students and returns the result
	 * of the plagiarism algorithm along with the snippets data.
	 * @param fileList1 a list of files
	 * @param fileList2 another list of files
	 * @return a FilePair that contains the result of the comparision
	 */
	List<IFilePair> compareFilesForResult(Collection<File> fileList1, Collection<File> fileList2);
	
	/**
	 * This method generates the snippet data for the HW files of two students 
	 * and returns the snippet data.
	 * @param student1Id Integer
	 * @param student2Id Integer
	 * @return codeSnippet CodeSnippet
	 */
	ICodeSnippets generateSnippet(Integer student1Id, Integer student2Id);
	
	/**
	 * Getter for studentHWMap. This method is made for testing purposes.
	 * @return studentHWMap Map<Integer, Collection<File>>
	 */
	Map<Integer, Collection<File>> getStudentHWMap();
	
	/**
	 * This method returns the name of the student given the id of the student.
	 * @param studentId the student's id
	 * @return the name of the student
	 */
	String getNameById(Integer studentId);

	/**
	 * Get the email of the student by his/her Id
	 * @param studentId the Id of the student
	 * @return the email of the student
	 */
	String getEmailById(Integer studentId);
	
	/**
	 * This method resets the state of the application and clears all the parameters.
	 * 
	 */
	void resetState();

	/**
	 * gets the repo paths
	 * @return repoPaths a list of repository paths
	 */
	List<String> getRepoPaths();
	
	/**
	 * gets the hw directories.
	 * @return hwDir String
	 */
	String getHWDir();
	
}
