function main() {
    startApplication("plagiarism-detector-0.0.1-SNAPSHOT-jfx.jar");
    mouseClick(waitForObject(":OK_button_2"), 37, 15, 0, Button.Button1);
    mouseClick(waitForObject(":final-test-repos_check-box"), 49, 31, 0, Button.Button1);
    chooseDirectory(waitForObject(":SquishJavaFX"), "C:\\Study\\MSD\\TeamRepo\\team-107\\plagiarism-detector\\src\\test\\resources\\final-test-repos");
    mouseClick(waitForObject(":final-test-repos_check-box_2"), 9, 12, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.hw_text-input text-field"), 43, 1, 0, Button.Button1);
    type(waitForObject(":Integrity Plagiarism Checker by Team-107.hw_text-input text-field"), "HW3");
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.Upload Excel Validator_button danger"), 135, 14, 0, Button.Button1);
    chooseFile(waitForObject(":SquishJavaFX"), "C:\\Study\\MSD\\TeamRepo\\team-107\\plagiarism-detector\\src\\test\\resources\\studentData.xlsx");
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.Run_button primary"), 47, 15, 0, Button.Button1);
    mouseClick(waitForObject(":OK_button_2"), 21, 14, 0, Button.Button1);
    doubleClick(waitForObject(":Student-101 - Student-105.Student-101 - Student-105_text"), 125, 3, 0, Button.Button1);
    doubleClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    doubleClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    doubleClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    doubleClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.>_button danger"), 25, 24, 0, Button.Button1);
    mouseClick(waitForObject(":Integrity Plagiarism Checker by Team-107.Reveal Names_button success"), 88, 18, 0, Button.Button1);
    snooze(2.3);
    closeWindow(":Integrity Plagiarism Checker by Team-107_Stage");
}
